 [build]
 publish = "dist" # Ensure this points to your build folder
  command = "npm run build" # Adjust this if your build command is different
 [[redirects]]
  from = "/*"
  to = "\Grocery-Store-Project2\web project\GroceryStore\php\Home.php"
  status = 200